apiVersion: v1
kind: ConfigMap
metadata:
  name: safeashouses-ingest-config
  labels:
    app: safeashouses
data:
  ES_URL: http://safeashouses-elastic:9200
  QUERY_URL: https://www.rightmove.co.uk/property-for-sale/find.html?searchType=SALE&locationIdentifier=REGION%5E70438&insId=1&radius=0.0&minPrice=800000&maxPrice=1250000&minBedrooms=&maxBedrooms=&displayPropertyType=&maxDaysSinceAdded=&_includeSSTC=on&sortByPriceDescending=&primaryDisplayPropertyType=&secondaryDisplayPropertyType=&oldDisplayPropertyType=&oldPrimaryDisplayPropertyType=&newHome=&auction=false
  INDEX_NAME: house-index
  PARALLELISM: "10"