apiVersion: v1
kind: ConfigMap
metadata:
  name: safeashouses-ingest-config
data:
  ES_URL: http://safeashouses-elastic:9200
  QUERY_URL: https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=USERDEFINEDAREA%5E%7B%22id%22%3A%228084083%22%7D&minBedrooms=2&maxPrice=1750000&minPrice=800000&propertyTypes=&mustHave=&dontShow=&furnishTypes=&keywords=
  INDEX_NAME: house-index-6
  PARALLELISM: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: safeashouses-server-config
data:
  SCRAPEMOVE_ES_URL: http://safeashouses-elastic:9200
  SCRAPEMOVE_ES_INDEX: house-index-6
  SCRAPEMOVE_SERVER_HOST: 0.0.0.0
  SCRAPEMOVE_SERVER_PORT: "80"