apiVersion: batch/v1
kind: CronJob
metadata:
  name: safeashouses-ingest
  labels:
    app: safeashouses
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: safeashouses-ingest
              image: briggysmalls/safeashouses-ingest:50c29144
              envFrom:
                - configMapRef:
                    name: safeashouses-ingest-config
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "0.7"
          restartPolicy: OnFailure