apiVersion: batch/v1
kind: CronJob
metadata:
  name: safeashouses-ingest
spec:
  schedule: "0 0,12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: safeashouses-ingest
              image: safeashouses-ingest
              envFrom:
                - configMapRef:
                    name: safeashouses-ingest-config
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "0.7"
          restartPolicy: OnFailure