resources:
- config.yaml
- ingest.yaml
- server.yaml
- elastic.yaml

namespace: default

commonLabels:
  app: safeashouses

images:
  - name: safeashouses-ingest
    newName: briggysmalls/safeashouses-ingest
    newTag: latest
  - name: safeashouses-server
    newName: briggysmalls/safeashouses-ui
    newTag: latest