apiVersion: v1
kind: Service
metadata:
  name: safeashouses-server
  labels:
    app: safeashouses
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      name: http
  selector:
    app: safeashouses
    tier: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safeashouses-server
  labels:
    app: safeashouses
spec:
  selector:
    matchLabels:
      app: safeashouses
      tier: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: safeashouses
        tier: server
    spec:
      containers:
      - image: docker.io/briggysmalls/safeashouses-ui
        name: safeashouses-server
        ports:
          - containerPort: 80
            name: http
        envFrom:
          - configMapRef:
              name: safeashouses-server-config