name: CI

on: [push]

jobs:
  build-server:
    uses: ./.github/workflows/docker-build.yaml
    with:
      directory: scrapemove-ui
      image-name: safeashouses-ui
    secrets: inherit

  build-ingest:
    uses: ./.github/workflows/docker-build.yaml
    with:
      directory: house_ingest
      image-name: safeashouses-ingest
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: [build-server, build-ingest]
    steps:
      - uses: actions/checkout@v1
      - uses: imranismail/setup-kustomize@v2
      - run: |
          cd deploy
          kustomize edit set image \
            briggysmalls/safeashouses-ingest:${GITHUB_SHA} \
            briggysmalls/safeashouses-ui:${GITHUB_SHA}
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k ./deploy