on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      directory:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create GITHUB_SHORT_SHA env var
        run: echo "GITHUB_SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ inputs.directory }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            briggysmalls/${{ inputs.image-name }}:${{ env.GITHUB_SHORT_SHA }}
            briggysmalls/${{ inputs.image-name }}:latest